[variables]
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'

[phases.setup]
nixPkgs = ['nodejs', 'jq']

[phases.caddy]
dependsOn = ['setup']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
nixPkgs = ['caddy']

[phases.fmt]
dependsOn = ['caddy']
cmds = ['caddy fmt --overwrite Caddyfile']

[phases.build]
dependsOn = ['setup']
cmds = [
  'npm install',
  'npm run build -- --configuration production'
]

[start]
cmd = 'caddy run --config Caddyfile --adapter caddyfile'
